- block:
  - name: Install Zabbix repo
    package:
      name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
      state: present

  - name: Install zabbix-agent package
    package:
      name: "zabbix-agent"
      state: latest


  - block:
    - name: Setup Zabbix agent (Hostname={{ hostname }})
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: '^Hostname='
        line: 'Hostname={{ hostname }}'
      notify: Restart and enable zabbix-agent

    - name: Setup Zabbix agent (Server={{ zabbix_server }})
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: '^Server='
        line: 'Server={{ zabbix_server }}'
      notify: Restart and enable zabbix-agent

    - name: Setup Zabbix agent (ServerActive={{ zabbix_server }})
      lineinfile:
        dest: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: '^ServerActive='
        line: 'ServerActive={{ zabbix_server }}'
      notify: Restart and enable zabbix-agent
    when: hostname is defined and hostname != None


  - name: Start and enable zabbix-agent
    service:
      name: zabbix-agent
      state: started
      enabled: yes
  when: zabbix_server is defined and zabbix_server != None and hostname is defined and hostname != None
