- block:
    - name: Install 'xz-utils' package
      package:
        state: present
        name:
          - xz-utils

    - name: Install Zabbix repo
      apt:
        deb: https://repo.zabbix.com/zabbix/5.0/debian/pool/main/z/zabbix-release/zabbix-release_5.0-2+debian11_all.deb
        state: present

    - name: Install zabbix-agent package
      package:
        state: latest
        name:
          - zabbix-agent


    - block:
        - name: Setup Zabbix agent 'Hostname={{ hostname }}'
          lineinfile:
            dest: /etc/zabbix/zabbix_agentd.conf.d/hostname.conf
            state: present
            create: yes
            regexp: '^Hostname='
            line: 'Hostname={{ hostname }}'
          notify: Restart and enable zabbix-agent

        - name: Setup Zabbix agent 'Server={{ zabbix_server }}'
          lineinfile:
            dest: /etc/zabbix/zabbix_agentd.conf.d/server.conf
            state: present
            create: yes
            regexp: '^Server='
            line: 'Server={{ zabbix_server }}'
          notify: Restart and enable zabbix-agent

        - name: Setup Zabbix agent 'ServerActive={{ zabbix_server }}'
          lineinfile:
            dest: /etc/zabbix/zabbix_agentd.conf.d/server_active.conf
            state: present
            create: yes
            regexp: '^ServerActive='
            line: 'ServerActive={{ zabbix_server }}'
          notify: Restart and enable zabbix-agent
      when: hostname is defined and hostname != None
  when: zabbix_server is defined and zabbix_server != None and hostname is defined and hostname != None
