ansible_host: 10.1.1.1
ansible_port: 22222
ansible_user: vagrant

ansible_ssh_private_key_file: ~/.ssh/id_rsa
#ansible_ssh_private_key_file: ../../vagrant/centos7/lin/.vagrant/machines/default/virtualbox/private_key

hostname: vagrant-lin
tuned_profile: virtual-guest
sudo_user: zzz
