alias ifs='/usr/bin/ifstat'
alias ift='iftop -B -P -N'
alias me='mcedit'
alias t1='top -d 1'
alias taila='tailf /var/log/httpd/access_log'
alias tailm='tailf /var/log/messages'
alias tailn='tailf /var/log/nginx/access.log'
