- hosts: all

  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: scripts
      tags: scripts
    - role: zabbix-agent
      tags: zabbix-agent
    - role: deploy-tool
      tags: deploy-tool
